### ISSUE TITLE
How do I write to each address?

### ISSUE THREAD

**Issue by orbitrod** [mortonkopf/OneWire_DS2413_array#1]
I am using your sketch to improve Adafruit's example sketch for the DS2413.
https://github.com/adafruit/Adafruit_DS2413/blob/master/DS2413.pde

Their sketch only reads 1 address and only allows you to write to 1 address.

I was able to get their sketch to read all the DS2413 addresses connected, but how can I write to each address?

**Comment by mortonkopf** [comment]
Hi orbitrod. I have some code that writes to each address in a loop using values stored in an array. I shall post it here within a few days.

**Comment by orbitrod** [comment]
Thanks a lot mortonkopf!  You are one of the few guys out there with with an example sketch for the DS2413, so I greatly appreciate the help!

**Comment by mortonkopf** [comment]
So, having some trouble remembering how this worked, as I moved over to a different chip. From my files I think that it was as simple as using the write function: 
/*
0x0 (B00000000) - Both pins LOW
0x1 (B00000001) - IOA = HIGH, IOB = LOW
0x2 (B00000010) - IOA = LOW, IOB = HIGH
0x3 (B00000011) - Both pins HIGH
0xFF (B11111111) - Read Failed!
*/
bool write(uint8_t state)
{
  uint8_t ack = 0;
  
  /* Top six bits must '1' */
  state |= 0xFC;
  
  oneWire.reset();
  oneWire.select(address);
  oneWire.write(DS2413_ACCESS_WRITE);
  oneWire.write(state);
  oneWire.write(~state);                    /* Invert data and resend     */    
  ack = oneWire.read();                     /* 0xAA=success, 0xFF=failure */  
  if (ack == DS2413_ACK_SUCCESS)
  {
    oneWire.read();                          /* Read the status byte      */
  }
  oneWire.reset();
    
  return (ack == DS2413_ACK_SUCCESS ? true : false);
}

I have a sketch associated with that work, but no longer have the hardware to test it. From reading the sketch i will post, it looks like it was working for the button array to read values, but also read the values. I moved over to the DS28EA chip for these button grids. I will post the example now

**Comment by orbitrod** [comment]
Hi @mortonkopf 

Your DS2413_button_array_test sketch worked perfectly out of the box!  All I had to do is change the DS2413_ONEWIRE_PIN pin definition.

I posted images of it working and you gave you credit on the Adafruit forum.  Here is the link 
https://forums.adafruit.com/viewtopic.php?f=8&t=139115

Thank you for all your help!

**Comment by mortonkopf** [comment]
Great. thanks for confirming it works for you, always nice to see a piece of code in use. I was surprised that it functioned as expected as it was a long time ago. 

Hopefully the signpost on the adafruit site will allow others to do it stress free. Not sure why this approach is not part of the standard library for the device.

M

**Comment by orbitrod** [comment]
Yeah I hope it helps others too.  This seems like such a simple task, but there are NO examples out there that show you how to read multiple DS2413s and write to the PIOs.  **Yours is the only one.**  Thank you for putting this information out there and helping me get this working.
